title: rilikoss media
description: typography explained
footer_text: Copyright 2021 rilikoss media
header_feature_image: ../uploads/alice-donovan-rouse-yu68fuqdvoi-unsplash.jpg
header_text: rilikoss media
header_text_color: "#000000"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/rilikossmedialogo.png
favicon: ../uploads/rilikossmedialogo.png
gridlayout: true
fixednavbar: false
upzoom: true
