title: rilikoss media
description: styles of typography explained.
footer_text: Copyright 2021 rilikoss media
header_feature_image: ../uploads/typewriterphoto.jpeg
header_text: rilikoss media
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/rilikossmedialogo.png
favicon: ../uploads/rilikossmedialogo.png
gridlayout: false
fixednavbar: false
upzoom: true
