title: rilikoss media
description: The uses of typography in marketing
footer_text: Copyright 2021 rilikoss media
header_feature_image: ../uploads/alice-donovan-rouse-yu68fuqdvoi-unsplash.jpg
header_text: rilikoss media
header_text_color: "#ff0000"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/rilikossmedialogo.png
favicon: ../uploads/rilikossmedialogo.png
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme/
