title: rilikoss media
description: Articles of your choice
footer_text: Copyright 2021 rilikoss media
header_feature_image: ../uploads/typewriterphoto.jpeg
header_text: rilikoss media
header_text_color: "#17bfcb"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
